/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urnaeletronica;

import java.io.IOException;

/**
 *
 * @author Yuri
 */
public class UrnaUI extends javax.swing.JFrame {
    static Cliente cliente;
    
    static int iModoUI = 0;
    
    /**
     * Creates new form UrnaUI
     */
    public UrnaUI() {
        initComponents();
        jLabelSelErroLista.setVisible(false);
        jLabelSelOpInvalida1.setVisible(false);
        jLabelConfirma1.setVisible(false);
        jLabelConfirma2.setVisible(false);
    }
    
    /**
     *
     * @throws IOException
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelBotao = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonCorrige = new javax.swing.JButton();
        jButtonConfirma = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jPanelVota = new javax.swing.JPanel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelNomeSpace = new javax.swing.JLabel();
        jLabelPartido = new javax.swing.JLabel();
        jLabelPartSpace = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelNumSpace = new javax.swing.JLabel();
        jLabelConfirma1 = new javax.swing.JLabel();
        jLabelConfirma2 = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();
        jPanelFinal = new javax.swing.JPanel();
        jLabelFinal1 = new javax.swing.JLabel();
        jLabelFinal2 = new javax.swing.JLabel();
        jPanelCarrega = new javax.swing.JPanel();
        jLabelCarrega = new javax.swing.JLabel();
        jPanelNaoEncontrado = new javax.swing.JPanel();
        jLabelAviso2 = new javax.swing.JLabel();
        jLabelAviso1 = new javax.swing.JLabel();
        jPanelSelecao = new javax.swing.JPanel();
        jLabelSel2 = new javax.swing.JLabel();
        jLabelSelNumSpace = new javax.swing.JLabel();
        jLabelSel3 = new javax.swing.JLabel();
        jLabelSel1 = new javax.swing.JLabel();
        jLabelSelErroLista = new javax.swing.JLabel();
        jLabelSelOpInvalida1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabelTitulo.setText("Urna Eletrônica");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jPanelBotao.setBackground(new java.awt.Color(51, 51, 51));
        jPanelBotao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setMaximumSize(new java.awt.Dimension(43, 31));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 68, 40));

        jButtonCorrige.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCorrige.setText("CORRIGE");
        jButtonCorrige.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorrigeActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButtonCorrige, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 125, 60));

        jButtonConfirma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonConfirma.setText("CONFIRMA");
        jButtonConfirma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButtonConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 125, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setMaximumSize(new java.awt.Dimension(43, 31));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 68, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setMaximumSize(new java.awt.Dimension(43, 31));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 68, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setMaximumSize(new java.awt.Dimension(43, 31));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 68, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setMaximumSize(new java.awt.Dimension(43, 31));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 68, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setMaximumSize(new java.awt.Dimension(43, 31));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 68, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setMaximumSize(new java.awt.Dimension(43, 31));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 68, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setMaximumSize(new java.awt.Dimension(43, 31));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 68, 40));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setMaximumSize(new java.awt.Dimension(43, 31));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 68, 40));

        jButton0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton0.setMaximumSize(new java.awt.Dimension(43, 31));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanelBotao.add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 68, 40));

        getContentPane().add(jPanelBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 432, 451));

        jPanelVota.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNumero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNumero.setText("Número:");
        jPanelVota.add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 68, -1, -1));

        jLabelNomeSpace.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNomeSpace.setText(" ");
        jPanelVota.add(jLabelNomeSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 320, -1));

        jLabelPartido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPartido.setText("Partido:");
        jPanelVota.add(jLabelPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 253, -1, -1));

        jLabelPartSpace.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPartSpace.setText(" ");
        jPanelVota.add(jLabelPartSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 270, -1));

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNome.setText("Nome:");
        jPanelVota.add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 160, -1, -1));

        jLabelNumSpace.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNumSpace.setText(" ");
        jPanelVota.add(jLabelNumSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 68, 268, -1));

        jLabelConfirma1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelConfirma1.setText("Este é o candidato desejado?");
        jPanelVota.add(jLabelConfirma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabelConfirma2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelConfirma2.setText("Se sim, aperte CONFIRMA");
        jPanelVota.add(jLabelConfirma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));
        jPanelVota.add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 170, 190));

        getContentPane().add(jPanelVota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 600, 450));

        jPanelFinal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFinal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFinal1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelFinal1.setText("Votações finalizadas");
        jPanelFinal.add(jLabelFinal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabelFinal2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelFinal2.setText("Aperte CONFIRMA para sair");
        jPanelFinal.add(jLabelFinal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        getContentPane().add(jPanelFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 600, 450));

        jPanelCarrega.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCarrega.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCarrega.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelCarrega.setText("Lista de candidatos carregada");
        jPanelCarrega.add(jLabelCarrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        getContentPane().add(jPanelCarrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 600, 450));
        jPanelCarrega.getAccessibleContext().setAccessibleName("");

        jPanelNaoEncontrado.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNaoEncontrado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAviso2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelAviso2.setText("Aperte CORRIGE");
        jPanelNaoEncontrado.add(jLabelAviso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabelAviso1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelAviso1.setText("Candidato não encontrado");
        jPanelNaoEncontrado.add(jLabelAviso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        getContentPane().add(jPanelNaoEncontrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 600, 450));

        jPanelSelecao.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSelecao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSel2.setText("2- Votar em branco");
        jPanelSelecao.add(jLabelSel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 160, -1, -1));

        jLabelSelNumSpace.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSelNumSpace.setText(" ");
        jLabelSelNumSpace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSelecao.add(jLabelSelNumSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, -1));

        jLabelSel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSel3.setText("3- Votar nulo");
        jPanelSelecao.add(jLabelSel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 253, -1, -1));

        jLabelSel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSel1.setText("1- Escolher candidato");
        jPanelSelecao.add(jLabelSel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 68, -1, -1));

        jLabelSelErroLista.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSelErroLista.setText("Lista não carregada");
        jPanelSelecao.add(jLabelSelErroLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 290, -1));

        jLabelSelOpInvalida1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSelOpInvalida1.setText("Operação Inválida");
        jPanelSelecao.add(jLabelSelOpInvalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 290, -1));

        getContentPane().add(jPanelSelecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        if(cliente.getsOp().isEmpty() == true)
            cliente.setsOp("0");
        else
            cliente.setsOp(cliente.getsOp().concat("0"));
        
        if(iModoUI == 0){
            jLabelSelNumSpace.setText(cliente.getsOp());
        }
        else if(iModoUI == 1){
            jLabelNumSpace.setText(cliente.getsOp());
            verificaCandidato();
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(cliente.getsOp().isEmpty() == true)
            cliente.setsOp("9");
        else
            cliente.setsOp(cliente.getsOp().concat("9"));
        
        if(iModoUI == 0){
            jLabelSelNumSpace.setText(cliente.getsOp());
        }
        else if(iModoUI == 1){
            jLabelNumSpace.setText(cliente.getsOp());
            verificaCandidato();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(cliente.getsOp().isEmpty() == true)
            cliente.setsOp("8");
        else
            cliente.setsOp(cliente.getsOp().concat("8"));
        
        if(iModoUI == 0){
            jLabelSelNumSpace.setText(cliente.getsOp());
        }
        else if(iModoUI == 1){
            jLabelNumSpace.setText(cliente.getsOp());
            verificaCandidato();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(cliente.getsOp().isEmpty() == true)
            cliente.setsOp("7");
        else
            cliente.setsOp(cliente.getsOp().concat("7"));
        
        if(iModoUI == 0){
            jLabelSelNumSpace.setText(cliente.getsOp());
        }
        else if(iModoUI == 1){
            jLabelNumSpace.setText(cliente.getsOp());
            verificaCandidato();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(cliente.getsOp().isEmpty() == true)
            cliente.setsOp("6");
        else
            cliente.setsOp(cliente.getsOp().concat("6"));
        
        if(iModoUI == 0){
            jLabelSelNumSpace.setText(cliente.getsOp());
        }
        else if(iModoUI == 1){
            jLabelNumSpace.setText(cliente.getsOp());
            verificaCandidato();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(cliente.getsOp().isEmpty() == true)
            cliente.setsOp("4");
        else
            cliente.setsOp(cliente.getsOp().concat("4"));
        
        if(iModoUI == 0){
            jLabelSelNumSpace.setText(cliente.getsOp());
        }
        else if(iModoUI == 1){
            jLabelNumSpace.setText(cliente.getsOp());
            verificaCandidato();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(cliente.getsOp().isEmpty() == true)
            cliente.setsOp("5");
        else
            cliente.setsOp(cliente.getsOp().concat("5"));
        
        if(iModoUI == 0){
            jLabelSelNumSpace.setText(cliente.getsOp());
        }
        else if(iModoUI == 1){
            jLabelNumSpace.setText(cliente.getsOp());
            verificaCandidato();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(cliente.getsOp().isEmpty() == true)
            cliente.setsOp("3");
        else
            cliente.setsOp(cliente.getsOp().concat("3"));
        
        if(iModoUI == 0){
            jLabelSelNumSpace.setText(cliente.getsOp());
        }
        else if(iModoUI == 1){
            jLabelNumSpace.setText(cliente.getsOp());
            verificaCandidato();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(cliente.getsOp().isEmpty() == true)
            cliente.setsOp("2");
        else
            cliente.setsOp(cliente.getsOp().concat("2"));
        
        if(iModoUI == 0){
            jLabelSelNumSpace.setText(cliente.getsOp());
        }
        else if(iModoUI == 1){
            jLabelNumSpace.setText(cliente.getsOp());
            verificaCandidato();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaActionPerformed
        // TODO add your handling code here:
        if(iModoUI == 0){
            if(cliente.isbLoaded()){
                if(cliente.getsOp().equals("1")){
                    iModoUI = 1;
                    cliente.setsOp("");
                }
                else if((cliente.getsOp().equals("2") ||
                        (cliente.getsOp().equals("3")))){
                    cliente.setbConfirma(true);
                    while(cliente.isbConfirma());
                    limpa();
                }
                else if(cliente.getsOp().equals("888")){
                    cliente.setbConfirma(true);
                    while(cliente.isbConfirma());
                    limpa();
                    iModoUI = 4;
                }
                else
                    jLabelSelOpInvalida1.setVisible(true);
            }
            else{
                if(cliente.getsOp().equals("999")){
                    cliente.setbConfirma(true);
                    while(cliente.isbConfirma());
                    limpa();
                    iModoUI = 3;
                }
                else if((cliente.getsOp().equals("1")) ||
                        (cliente.getsOp().equals("2")) ||
                        (cliente.getsOp().equals("3")) ||
                        (cliente.getsOp().equals("888")))
                    jLabelSelErroLista.setVisible(true);
                else
                    jLabelSelOpInvalida1.setVisible(true);
            }
        } else if(iModoUI == 1){
            if(verificaCandidato() == true){
                cliente.setbConfirma(true);
                while(cliente.isbConfirma());
                limpa();
                iModoUI = 0;
            }
        } else if(iModoUI == 3){
            cliente.setsOp("");
            jLabelSelNumSpace.setText(" ");
            iModoUI = 0;
        } else if(iModoUI == 4){
            limpa();
            iModoUI = 0;
            cliente.setbLoaded(false);
        }
    }//GEN-LAST:event_jButtonConfirmaActionPerformed

    private void jButtonCorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorrigeActionPerformed
        // TODO add your handling code here:
        limpa();
        
        if(iModoUI == 2){
            iModoUI = 1;
        }
    }//GEN-LAST:event_jButtonCorrigeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(cliente.getsOp().isEmpty() == true)
            cliente.setsOp("1");
        else
            cliente.setsOp(cliente.getsOp().concat("1"));
        
        if(iModoUI == 0){
            jLabelSelNumSpace.setText(cliente.getsOp());
        }
        else if(iModoUI == 1){
            jLabelNumSpace.setText(cliente.getsOp());
            verificaCandidato();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrnaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrnaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrnaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrnaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UrnaUI ui = new UrnaUI();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrnaUI().setVisible(true);
            }
        });
        
        cliente = new Cliente();
        Thread UErun = new Thread(cliente);
        
        /* Tratamento da interface */
        Thread tratamentoUI = new Thread(new Runnable (){
            @Override
            public void run() {
                tratamentoDeTelas();
            }
        });
        
        tratamentoUI.start();
        UErun.start();
    }
    
    // Procura o numero do candidato na lista recebida
    private boolean verificaCandidato() {
        boolean bEncontra=false;
        if(jLabelNumSpace.getText().length() == 5){
            for(int i=0; i<cliente.getiTamanhoLista(); i++){
                if(Integer.parseInt(jLabelNumSpace.getText()) == cliente.getiCodigoVotacao(i)){
                    jLabelNomeSpace.setText(cliente.getsNomeCandidato(i));
                    jLabelPartSpace.setText(cliente.getsPartidoCandidato(i));
                    jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource(cliente.getsFilePathCandidato(i))));
                    
                    jLabelConfirma1.setVisible(true);
                    jLabelConfirma2.setVisible(true);
                    
                    bEncontra=true;
                }
            }
            if(bEncontra==false){
                iModoUI=2;
            }
        }
        return bEncontra;
    }
    
    // Faz o tratamento a partir de setVisible()
    private static void tratamentoDeTelas() {
        while(true){
            // Selecao de opcao
            if(iModoUI == 0){
                jPanelSelecao.setVisible(true);
                jPanelVota.setVisible(false);
                jPanelNaoEncontrado.setVisible(false);
                jPanelCarrega.setVisible(false);
                jPanelFinal.setVisible(false);
            }
            // Voto do cliente
            else if(iModoUI == 1){
                jPanelSelecao.setVisible(false);
                jPanelVota.setVisible(true);
                jPanelNaoEncontrado.setVisible(false);
                jPanelCarrega.setVisible(false);
                jPanelFinal.setVisible(false);
            }
            // Candidato nao encontrado
            else if(iModoUI == 2){
                jPanelSelecao.setVisible(false);
                jPanelVota.setVisible(false);
                jPanelNaoEncontrado.setVisible(true);
                jPanelCarrega.setVisible(false);
                jPanelFinal.setVisible(false);
            }
            // Carregar lista de candidatos
            else if(iModoUI == 3){
                jPanelSelecao.setVisible(false);
                jPanelVota.setVisible(false);
                jPanelNaoEncontrado.setVisible(false);
                jPanelCarrega.setVisible(true);
                jPanelFinal.setVisible(false);
            }
            // Finalizar votacoes
            else if(iModoUI == 4){
                jPanelSelecao.setVisible(false);
                jPanelVota.setVisible(false);
                jPanelNaoEncontrado.setVisible(false);
                jPanelCarrega.setVisible(false);
                jPanelFinal.setVisible(true);
            }
        }
    }
    
    // Limpa conteúdo da barra de texto e erros de operação
    private void limpa(){
        cliente.setsOp("");
        
        jLabelNumSpace.setText(" ");
        jLabelNomeSpace.setText(" ");
        jLabelPartSpace.setText(" ");
        jLabelImagem.setIcon(null);
        jLabelConfirma1.setVisible(false);
        jLabelConfirma2.setVisible(false);
        
        jLabelSelNumSpace.setText(" ");
        jLabelSelOpInvalida1.setVisible(false);
        jLabelSelErroLista.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonConfirma;
    private javax.swing.JButton jButtonCorrige;
    private static javax.swing.JLabel jLabelAviso1;
    private static javax.swing.JLabel jLabelAviso2;
    private static javax.swing.JLabel jLabelCarrega;
    private static javax.swing.JLabel jLabelConfirma1;
    private static javax.swing.JLabel jLabelConfirma2;
    private static javax.swing.JLabel jLabelFinal1;
    private static javax.swing.JLabel jLabelFinal2;
    private static javax.swing.JLabel jLabelImagem;
    private static javax.swing.JLabel jLabelNome;
    private static javax.swing.JLabel jLabelNomeSpace;
    private static javax.swing.JLabel jLabelNumSpace;
    private static javax.swing.JLabel jLabelNumero;
    private static javax.swing.JLabel jLabelPartSpace;
    private static javax.swing.JLabel jLabelPartido;
    private static javax.swing.JLabel jLabelSel1;
    private static javax.swing.JLabel jLabelSel2;
    private static javax.swing.JLabel jLabelSel3;
    private static javax.swing.JLabel jLabelSelErroLista;
    private static javax.swing.JLabel jLabelSelNumSpace;
    private static javax.swing.JLabel jLabelSelOpInvalida1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelBotao;
    private static javax.swing.JPanel jPanelCarrega;
    private static javax.swing.JPanel jPanelFinal;
    private static javax.swing.JPanel jPanelNaoEncontrado;
    private static javax.swing.JPanel jPanelSelecao;
    private static javax.swing.JPanel jPanelVota;
    // End of variables declaration//GEN-END:variables
}
